#Instead of using TAB for indentation, use two spaces at the place of one TAB

Skyline:
  #Controller to control robot arm joints
  robot_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [joint_0, joint_1, joint_2, joint_3, joint_4]

  # hand_ee_controller:
  #   type: "position_controllers/JointTrajectoryController"
  #   joints: []

  #Controller to continuously publish joint states/positions
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50