<?xml version="1.0"?>
<!-- http://wiki.ros.org/urdf/XML/link  -->
<robot name="skyline_robot" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Macros -->
	<!-- lengths -->
	<xacro:property name="base_height" value = "1.0155" />
	<xacro:property name="arm_length" value = "2.8455" />
	<xacro:property name="wrist_length" value = "0.998302" />
	<xacro:property name="claw_length" value = "1.534561" />
	
	<!-- pyshical limits -->
	<xacro:macro name="joint_susan_y_limit">
		<limit effort="300" velocity="2.0" lower="0" upper="${2*pi}" />
	</xacro:macro>

	<xacro:macro name="base_arm_limit">
		<limit effort="300" velocity="2.0" lower="${-1*pi/2}" upper="${pi/2}" />
	</xacro:macro>

	<xacro:macro name="arm_joint_limit">
		<limit effort="300" velocity="2.0" lower="0" upper="${pi}" />
	</xacro:macro>

	<xacro:macro name="wrist_pitch_limit">
		<limit effort="300" velocity="2.0" lower="${-1*pi/2}" upper="${pi/2}" />
	</xacro:macro>

	<xacro:macro name="wrist_yaw_limit">
		<limit effort="300" velocity="2.0" lower="${-1*pi/2}" upper="${pi/2}" />
	</xacro:macro>

	<!-- axis of rotations -->
	<xacro:property name="yaw" value = "0 0 1" />
	<xacro:property name="pitch" value = "0 1 0" />
	<xacro:property name="roll" value = "1 0 0" />


	<!-- Base link -->
	<link name="link_base">
		<visual>
			<geometry>
				<cylinder length="0.1" radius="0.3"/>
			</geometry>
			
			<!--origin - the reference frame of the visul element with resppect to the reference frame of the link -->
			<!-- rpy -r is roll, p-pitch, and y -yaw -->
			<!-- xyz - x, y, z -offsets -->
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name = "yellow">
				<color rgba="1 1 0 1"/>
			</material>
		</visual>
	</link>


<!-- Lazy Susan Yaw Joint -->
	<!-- joint_susan_y -->
	<joint name="joint_susan_y" type="revolute">
		<parent link="link_base"/>
		<child link="link_susan_y"/>
			<origin xyz="0 0 0"/>
			<axis xyz="${yaw}"/>
			<xacro:joint_susan_y_limit/>
	</joint>

	<!-- link_susan -->
	<link name="link_susan_y">
	<visual>
		<geometry>
			<cylinder length="${base_height}" radius="0.1"/>
		</geometry>
			
		<origin rpy="0 0 0" xyz="0 0 ${base_height/2}"/>
		<material name = "blue">
			<color rgba="0 0 1 1"/>
		</material>
	</visual>
	</link>

<!-- Lazy Susan Pitch Joint -->
	<!-- joint_susan_pitch -->
	<joint name="joint_susan_p" type="revolute">
		<parent link="link_susan_y"/>
		<child link="link_susan_p"/>
			<origin xyz="0 0 ${base_height}"/>
			<axis xyz="${pitch}"/>
			<xacro:base_arm_limit/>
	</joint>

	<!-- link_susan_pitch -->
	<link name="link_susan_p">
	<visual>
		<geometry>
			<cylinder length="${arm_length}" radius="0.1"/>
		</geometry>
			
		<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
		<material name = "purple">
			<color rgba="1 0 1 1"/>
		</material>
	</visual>
	</link>


<!-- Mid Arm Joint -->
	<!-- joint_mid -->
	<joint name="joint_mid_p" type="revolute">
		<parent link="link_susan_p"/>
		<child link="link_mid_p"/>
			<origin xyz="0 0 ${arm_length}"/>
			<axis xyz="${pitch}"/>
			<xacro:arm_joint_limit/>
	</joint>

	<!-- link_mid -->
	<link name="link_mid_p">
	<visual>
		<geometry>
			<cylinder length="${arm_length}" radius="0.1"/>
		</geometry>
			
		<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
		<material name = "green">
			<color rgba="0 1 0 1"/>
		</material>
	</visual>
	</link>

<!-- Wrist Pitch Joint -->
	<!-- joint_wrist_pitch -->
	<joint name="joint_wrist_p" type="revolute">
		<parent link="link_mid_p"/>
		<child link="link_wrist_p"/>
			<origin xyz="0 0 ${arm_length}"/>
			<axis xyz="${pitch}"/>
			<xacro:wrist_pitch_limit/>
		</joint>

	<!-- link_wrist_pitch -->
	<link name="link_wrist_p">
	<visual>
		<geometry>
			<cylinder length="${wrist_length}" radius="0.1"/>
		</geometry>
			
		<origin rpy="0 0 0" xyz="0 0 ${wrist_length/2}"/>
		<material name = "red">
			<color rgba="1 0 0 1"/>
		</material>
	</visual>
	</link>

<!-- Wrist Roll Joint -->
	<!-- joint_wrist_roll -->
	<joint name="joint_wrist_r" type="revolute">
		<parent link="link_wrist_p"/>
		<child link="link_wrist_y"/>
			<origin xyz="0 0 ${wrist_length}"/>
			<axis xyz="${yaw}"/>
			<xacro:wrist_yaw_limit/>
	</joint>

	<!-- link_wrist_roll -->
	<link name="link_wrist_y">
	<visual>
		<geometry>
			<box size="0.1 0.3 ${claw_length}" />
		</geometry>
			
		<origin rpy="0 0 0" xyz="0 0 ${claw_length/2}"/>
		<material name = "blue">
			<color rgba="0 0 1 1"/>
		</material>
	</visual>
	</link>


</robot>
